# Generated by Django 4.0 on 2022-01-11 12:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('doctor_name', models.TextField()),
                ('doctor_email', models.TextField()),
                ('doctor_password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
