# Generated by Django 4.0.1 on 2022-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
