# Generated by Django 4.0 on 2022-01-12 14:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1234', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='speciality',
            field=models.CharField(default='222', max_length=30),
            preserve_default=False,
        ),
    ]
