# Generated by Django 4.0 on 2022-01-11 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
