# Generated by Django 4.0 on 2022-01-11 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_doctordetails_uuid_alter_doctordetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
