# Generated by Django 4.0 on 2022-01-11 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_doctordetails_id_alter_doctordetails_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='uuid',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
