# Generated by Django 4.0 on 2022-01-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_patientdetails_doctor_patientdetails_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('bloodpressure', models.FloatField()),
                ('pulse', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patientdetails')),
            ],
        ),
    ]
